services:
  - type: web
    name: gt-3d-backend
    env: node
    rootDir: gt-3D-backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false

